owner: rzlamrr # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portofolio
    url: https://www.rzlamrr.me
  - name: Prayer Time
    url: https://jadwal.rzlamrr.me
  - name: dvstDrive
    url: https://drive.rzlamrr.me

status-website:
  cname: status.rzlamrr.me
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: dvstLab status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
  theme: dark

workflowSchedule:
  graphs: "5 17 * * *"
  responseTime: "0 17 * * *"
  staticSite: "10 17 * * *"
  summary: "0 17 * * *"
  updateTemplate: "0 17 * * *"
  updates: "55 16 * * *"
  uptime: "*/15 * * * *"

i18n:
  footer: © 2022 [rzlamrr](https://rzlamrr.me)

skipDescriptionUpdate: true
skipTopicsUpdate: true
