owner: rzlamrr # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portofolio
    url: https://www.rzlamrr.my.id
  - name: dVishper
    url: https://vishper.rzlamrr.my.id
  - name: Islamiah
    url: https://islam.rzlamrr.my.id
  - name: SpeedTest
    url: https://speed.rzlamrr.my.id
  - name: Prayer Time
    url: https://jadwal.rzlamrr.my.id
  - name: Tasbih Online
    url: https://tasbih.rzlamrr.my.id
  - name: Awan Abadi
    url: https://awan.rzlamrr.my.id

status-website:
  cname: status.rzlamrr.my.id
  hideNavTitle: true
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/rzlamrr/status/imgbot/assets/upptime-icon.svg
  faviconSvg: https://raw.githubusercontent.com/rzlamrr/status/imgbot/assets/upptime-icon.svg
  name: dvstLab status
  navbar:
    - title: Home
      href: https://rzlamrr.my.id
    - title: Contact
      href: https://vishper.rzlamrr.my.id
    - title: GitHub
      href: https://github.com/$OWNER
  theme: night

workflowSchedule:
  graphs: "5 17 * * *"
  responseTime: "0 17 * * *"
  staticSite: "10 17 * * *"
  summary: "0 17 * * *"
  updateTemplate: "0 17 * * *"
  updates: "55 16 * * *"
  uptime: "*/15 * * * *"

i18n:
  footer: © 2023 [rzlamrr](https://rzlamrr.my.id)

skipDescriptionUpdate: true
skipTopicsUpdate: true
