# Change these first
owner: rzlamrr # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portofolio
    url: https://www.rzlamrr.me
  - name: Prayer Time
    url: https://jadwal.rzlamrr.me

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rzlamrr.me
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: dvstLab status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
  theme: dark

workflowSchedule:
  graphs: "5 17 * * *"
  responseTime: "0 17 * * *"
  staticSite: "10 17 * * *"
  summary: "0 17 * * *"
  updateTemplate: "0 17 * * *"
  updates: "55 16 * * *"
  uptime: "*/15 * * * *"

skipDescriptionUpdate: true
skipTopicsUpdate: true
